import { defineServer } from '@supergrowthai/plugin-dev-kit';
import type { ServerSDK } from '@supergrowthai/types';
import { GoogleGenerativeAI } from '@google/generative-ai';
import OpenAI from 'openai';
import type { ContentObject } from '@supergrowthai/plugin-dev-kit/content';

type AIProvider = 'gemini' | 'openai';

const SETTINGS_ID = 'plugin_config';

const topics = [
    "The Future of Renewable Energy",
    "A Beginner's Guide to Machine Learning",
    "The Importance of Mindfulness in a Hectic World",
    "Exploring the Deep Sea: Earth's Final Frontier",
    "The Rise of Vertical Farming",
];

const DEFAULT_PROMPT = `Generate a comprehensive blog post about "{topic}".

Please provide:
1. An engaging title (60-80 characters)
2. A brief excerpt/summary (150-200 words)
3. Full blog content (800-1500 words) with proper structure including introduction, main body with subheadings, and conclusion

Format the response as a valid JSON object with the following structure:
{
  "title": "Your engaging title here",
  "excerpt": "Brief summary here",
  "content": "Full blog content with proper markdown formatting. All newline characters inside the content string must be escaped as \\n."
}

Make the content engaging, informative, and SEO-friendly. Use markdown formatting for headings, lists, and emphasis.`;

async function generateAIBlogContent(topic: string, provider: AIProvider, apiKey: string, modelName: string): Promise<{ title: string; content: string; excerpt: string }> {
    const prompt = DEFAULT_PROMPT.replace('{topic}', topic);
    let responseText: string;

    try {
        switch (provider) {
            case 'gemini': {
                const genAI = new GoogleGenerativeAI(apiKey);
                const model = genAI.getGenerativeModel({
                    model: modelName,
                    generationConfig: {
                        responseMimeType: "application/json",
                    },
                });
                const result = await model.generateContent(prompt);
                const response = await result.response;
                responseText = response.text();
                try {
                    const cleanedResponse = responseText.replace(/```json/g, '').replace(/```/g, '');
                    return JSON.parse(cleanedResponse);
                } catch (e: any) {
                    console.error("Failed to parse Gemini JSON response:", responseText);
                    throw new Error("Failed to parse Gemini JSON response.");
                }
            }
            case 'openai': {
                const openai = new OpenAI({ apiKey });
                const completion = await openai.chat.completions.create({
                    model: modelName,
                    messages: [{ role: "user", content: prompt }],
                    temperature: 0.7,
                    max_tokens: 2000,
                    response_format: { type: "json_object" },
                });
                responseText = completion.choices[0]?.message?.content || '{}';
                console.log('OpenAI response text:', responseText);
                try {
                    return JSON.parse(responseText);
                } catch (e: any) {
                    console.error("Failed to parse OpenAI JSON response:", responseText);
                    throw new Error("Failed to parse OpenAI JSON response.");
                }
            }
            default:
                throw new Error(`Unsupported AI provider: ${provider}`);
        }
    } catch (err: any) {
        console.error(`Error calling ${provider} API:`, err);
        throw new Error(`Error calling ${provider} API: ${err.message}`);
    }
}

async function createAndPublishAIBlog(sdk: ServerSDK, provider: AIProvider, apiKey: string, modelName: string) {
    const topic = topics[Math.floor(Math.random() * topics.length)];
    const blogData = await generateAIBlogContent(topic, provider, apiKey, modelName);

    const contentObject: ContentObject = {
        version: 1,
        content: [
            {
                name: 'Paragraph',
                version: 1,
                data: [{ name: 'Text', version: 1, data: blogData.content }]
            }
        ]
    };

    const systemUser = await sdk.db.users.findOne({ username: 'system' });
    if (!systemUser) {
        throw new Error('System user not found. Please ensure a user with username "system" exists.');
    }

    let defaultCategory = await sdk.db.categories.findOne({});
    if (!defaultCategory) {
        defaultCategory = await sdk.db.categories.create({
            name: 'AI Generated',
            slug: 'ai-generated',
            description: 'Content generated by AI',
        });
    }
    
    const slug = blogData.title.toLowerCase().replace(/[^a-z0-9\s-]/g, '').replace(/\s+/g, '-').substring(0, 50);

    const blog = await sdk.db.blogs.create({
        title: blogData.title,
        slug,
        content: contentObject,
        excerpt: blogData.excerpt,
        status: 'draft',
        userId: systemUser._id,
        categoryId: defaultCategory._id,
        tagIds: [],
        metadata: { source: 'ai-blog-generator', author: provider }
    });

    console.log(`Blog generated with ${provider}: "${blog.title}" (ID: ${blog._id})`);
    return blog;
}

export default defineServer({
    hooks: {
        'every-minute-blog': async (sdk) => {
            try {
                console.log('[Scheduled Post] Running every-minute-blog hook...');
                const settings = await sdk.settings.get(SETTINGS_ID);

                if (!settings || !settings.aiProvider || !settings.schedule) {
                    console.log('[Scheduled Post] Plugin not fully configured.');
                    return { success: false, message: 'Plugin not fully configured.' };
                }

                const provider = settings.aiProvider as AIProvider;
                const apiKey = provider === 'gemini' ? settings.geminiApiKey : settings.openaiApiKey;
                const modelName = provider === 'gemini' ? settings.geminiModelName : settings.openaiModelName;

                if (!apiKey || !modelName) {
                    console.log(`[Scheduled Post] API key or model for ${provider} not configured.`);
                    return { success: false, message: `API key or model for ${provider} not configured.` };
                }

                const now = new Date();
                const currentHour = now.getUTCHours();
                const currentMinute = now.getUTCMinutes();

                console.log('[Scheduled Post] Current time:', now.toString());
                console.log('[Scheduled Post] Current UTC time:', now.toUTCString());

                const scheduledTimes = settings.schedule.split(',').map((time: string) => {
                    const [hour, minute] = time.trim().split(':');
                    return { hour: parseInt(hour, 10), minute: parseInt(minute, 10) };
                }).filter((time: { hour: number; minute: number; }) => !isNaN(time.hour) && !isNaN(time.minute));

                console.log('[Scheduled Post] Scheduled times (UTC):', scheduledTimes);

                const isScheduledTime = scheduledTimes.some((t: { hour: number; minute: number; }) => t.hour === currentHour && t.minute === currentMinute);

                if (!isScheduledTime) {
                    console.log('[Scheduled Post] Not a scheduled time. Skipping blog generation.');
                    return { success: false, message: 'Not a scheduled time.' };
                }

                console.log(`[Scheduled Post] Scheduled time detected. Starting blog generation with ${provider}...`);
                const blog = await createAndPublishAIBlog(sdk, provider, apiKey, modelName);
                return { success: true, message: `Successfully generated AI blog post.`, blogId: blog?._id };

            } catch (error: any) {
                console.error('[Scheduled Post] AI Blog Post Generator hook error:', error);
                return { success: false, message: `Failed to generate blog: ${error.message}` };
            }
        }
    },
    rpcs: {
        'scheduled-post:getSettings': async (sdk) => {
            const settings = await sdk.settings.get(SETTINGS_ID);
            return {
                aiProvider: settings?.aiProvider || 'gemini',
                geminiApiKey: settings?.geminiApiKey || '',
                geminiModelName: settings?.geminiModelName || 'gemini-1.5-flash',
                openaiApiKey: settings?.openaiApiKey || '',
                openaiModelName: settings?.openaiModelName || 'gpt-4',
                schedule: settings?.schedule || '10:00,17:00',
            };
        },
        'scheduled-post:saveSettings': async (sdk, newSettings) => {
            await sdk.settings.set(SETTINGS_ID, newSettings);
            return { success: true };
        }
    }
});